### ISSUE TITLE
斗图模式开启后卡死

### ISSUE THREAD

**Issue by grapeot** [grapeot/WechatForwardBot#5]
main.py里开了斗图模式后就卡这里了。。。(是不是因为主目录没有featuresall.txt导致的？还有就是HistoryImages有部分图片，但是执行DoutuRobot/dedupAndCopy.sh貌似不能转换成jpg生成jpgs目录)
log.txt
I0620 10:17:45.229037 7646 net.cpp:200] relu2 does not need backward computation.
I0620 10:17:45.229044 7646 net.cpp:200] conv2 does not need backward computation.
I0620 10:17:45.229051 7646 net.cpp:200] norm1 does not need backward computation.
I0620 10:17:45.229059 7646 net.cpp:200] pool1 does not need backward computation.
I0620 10:17:45.229066 7646 net.cpp:200] relu1 does not need backward computation.
I0620 10:17:45.229074 7646 net.cpp:200] conv1 does not need backward computation.
I0620 10:17:45.229136 7646 net.cpp:200] data does not need backward computation.
I0620 10:17:45.229159 7646 net.cpp:242] This network produces output prob
I0620 10:17:45.229194 7646 net.cpp:255] Network initialization done.
I0620 10:17:45.770469 7646 upgrade_proto.cpp:44] Attempting to upgrade input file specified using deprecated transformation parameters: /root/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0620 10:17:45.770537 7646 upgrade_proto.cpp:47] Successfully upgraded file specified using deprecated data transformation parameters.
W0620 10:17:45.770547 7646 upgrade_proto.cpp:49] Note that future Caffe releases will only support transform_param messages for transformation fields.
I0620 10:17:45.770555 7646 upgrade_proto.cpp:53] Attempting to upgrade input file specified using deprecated V1LayerParameter: /root/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0620 10:17:46.342845 7646 upgrade_proto.cpp:61] Successfully upgraded file specified using deprecated V1LayerParameter
I0620 10:17:46.438140 7646 net.cpp:744] Ignoring source layer loss
Traceback (most recent call last):
File "main.py", line 36, in 
DoutuProcessor('./DoutuFeatures.txt') # Uncomment to enable Dou Tu
File "/opt/WechatForwardBot/DoutuProcessor.py", line 29, in init
self.imageSearcher = ImageSearcher(doutuFeatureFn)
File "/opt/WechatForwardBot/ImageSearcher.py", line 35, in init
self.parseFeature(featurefn)
File "/opt/WechatForwardBot/ImageSearcher.py", line 60, in parseFeature
imgfn, hash, imgfeatures = line.split('\t')
ValueError: not enough values to unpack (expected 3, got 2)

@lgs3137 报告。

**Comment by grapeot** [comment]
是的，是因为没有featuresall.txt造成的。这个不能直接运行就直接斗图的，要读一下code，做一些训练才好的~

**Comment by lgs3137** [comment]
嗯，还有就是我dat下手动建jpgs目录下执行脚本就正常了。。。
但是目前 ERROR : list index out of range 还是不断抛出，只要群员发送非指令都抛...

**Comment by grapeot** [comment]
好哒~那我先close啦~

**Comment by lgs3137** [comment]
已经指定featuresall.txt了，但是文档里没说到featureCache.tsv是什么内容的，现在又卡找不到featureCache.tsv了，ImageSearcher.py只写到这是个cache，难道是featuresall.txt的副本么？

I0620 11:40:27.499838  8421 upgrade_proto.cpp:47] Successfully upgraded file specified using deprecated data transformation parameters.
W0620 11:40:27.499850  8421 upgrade_proto.cpp:49] Note that future Caffe releases will only support transform_param messages for transformation fields.
I0620 11:40:27.499857  8421 upgrade_proto.cpp:53] Attempting to upgrade input file specified using deprecated V1LayerParameter: /root/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0620 11:40:27.833488  8421 upgrade_proto.cpp:61] Successfully upgraded file specified using deprecated V1LayerParameter
I0620 11:40:27.926455  8421 net.cpp:744] Ignoring source layer loss
2017-06-20 11:40:27,992 : INFO : Caffe net initialized. Loading cache...
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    DoutuProcessor('./featuresall.txt')
  File "/opt/WechatForwardBot/DoutuProcessor.py", line 29, in __init__
    self.imageSearcher = ImageSearcher(doutuFeatureFn)
  File "/opt/WechatForwardBot/ImageSearcher.py", line 38, in __init__
    self.loadCache('./featureCache.tsv')
  File "/opt/WechatForwardBot/ImageSearcher.py", line 42, in loadCache
    lines = [ x.strip().split('\t') for x in open(fn) ]
FileNotFoundError: [Errno 2] No such file or directory: './featureCache.tsv'

**Comment by lgs3137** [comment]
@grapeot 我cp featuresall.txt featureCache.tsv后就不卡死了~
但是 /doutu 后抛

2017-06-20 11:48:37,101 : INFO : [Doutu] Begin processing...
2017-06-20 11:48:37,985 : INFO : [Doutu] imagemagick succeeded.
/usr/local/lib/python3.5/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
2017-06-20 11:48:40,073 : ERROR : join() argument must be str or bytes, not 'list'

**Comment by grapeot** [comment]
这个是个cache。是用`extractFeatures.py`生成的。但斗图部分要想跑起来比较复杂，目前还没有一个完整的文档，更多的是靠读代码来搞清楚要怎么用~

**Comment by lgs3137** [comment]
我看到incrementalExtractFeatures.sh有调用extractFeatures.py了，py里面貌似没有实现自动输出tsv文件吧？caffe生成的么？
